name: multiomics
dependencies:
  - python=3.12.0
  - pip
  - pip:
    - networkx==3.2.1
    - numpy==1.26.4
    - matplotlib==3.8.2
    - pandas==2.2.1
    - rdflib==7.0.0
    - scikit-learn==1.4.1.post1
    - scipy==1.12.0
    - sparqlwrapper==2.0.0

